export const animatedInputClass: string =
	"w-full text-gray-600 h-12 px-3 text-sm bg-white border-[1px] rounded-[4px] border-black border-opacity-20 outline-none focus:border-[#017DC3] focus:text-black transition duration-200";

export const province = [
	"Abra",
	"Agusan del Norte",
	"Agusan del Sur",
	"Aklan",
	"Albay",
	"Antique",
	"Apayao",
	"Aurora",
	"Basilan",
	"Bataan",
	"Batanes",
	"Batangas",
	"Benguet",
	"Biliran",
	"Bohol",
	"Bukidnon",
	"Bulacan",
	"Cagayan",
	"Camarines Norte",
	"Camarines Sur",
	"Camiguin",
	"Capiz",
	"Catanduanes",
	"Cavite",
	"Cebu",
	"Cotabato",
	"Davao de Oro (Compostela Valley)",
	"Davao del Norte",
	"Davao del Sur",
	"Davao Occidental",
	"Davao Oriental",
	"Dinagat Islands",
	"Eastern Samar",
	"Guimaras",
	"Ifugao",
	"Ilocos Norte",
	"Ilocos Sur",
	"Iloilo",
	"Isabela",
	"Kalinga",
	"La Union",
	"Laguna",
	"Lanao del Norte",
	"Lanao del Sur",
	"Leyte",
	"Maguindanao",
	"Marinduque",
	"Masbate",
	"Misamis Occidental",
	"Misamis Oriental",
	"Mountain Province",
	"Negros Occidental",
	"Negros Oriental",
	"Northern Samar",
	"Nueva Ecija",
	"Nueva Vizcaya",
	"Occidental Mindoro",
	"Oriental Mindoro",
	"Palawan",
	"Pampanga",
	"Pangasinan",
	"Quezon",
	"Quirino",
	"Rizal",
	"Romblon",
	"Samar (Western Samar)",
	"Sarangani",
	"Siquijor",
	"Sorsogon",
	"South Cotabato",
	"Southern Leyte",
	"Sultan Kudarat",
	"Sulu",
	"Surigao del Norte",
	"Surigao del Sur",
	"Tarlac",
	"Tawi-Tawi",
	"Zambales",
	"Zamboanga del Norte",
	"Zamboanga del Sur",
	"Zamboanga Sibugay",
];
